#ifndef CHUNK_H
#define CHUNK_H

#include "common.h"

#include "types/value.h"

#define FOREACH(OPERATION) \
  OPERATION(OP_CONSTANT) \
  OPERATION(OP_TRUE) OPERATION(OP_FALSE) \
  OPERATION(OP_VOID) OPERATION(OP_UNDEFINED) \
  OPERATION(OP_NEGATION) \
  OPERATION(OP_ADD) OPERATION(OP_SUBTRACT) \
  OPERATION(OP_MULTIPLY) OPERATION(OP_DIVIDE) \
  OPERATION(OP_POWER) \
  OPERATION(OP_NOT) \
  OPERATION(OP_EQUAL) \
  OPERATION(OP_GREATER) OPERATION(OP_LESS) \
  OPERATION(OP_GLOBAL_INITIALIZE) \
  OPERATION(OP_GLOBAL_SET) OPERATION(OP_GLOBAL_GET) \
  OPERATION(OP_UP_SET) OPERATION(OP_UP_GET) \
  OPERATION(OP_LOCAL_SET) OPERATION(OP_LOCAL_GET) \
  OPERATION(OP_LOOP) OPERATION(OP_LOOP_CONDITIONAL) \
  OPERATION(OP_JUMP) OPERATION(OP_JUMP_CONDITIONAL) \
  OPERATION(OP_POP) OPERATION(OP_POP_N) \
  OPERATION(OP_CALL) OPERATION(OP_RETURN) \
  OPERATION(OP_CLOSURE) \
  OPERATION(OP_CLOSE) \
  OPERATION(OP_CLASS) \
  OPERATION(OP_MEMBER) OPERATION(OP_METHOD) \
  OPERATION(OP_PROPERTY_SET) OPERATION(OP_PROPERTY_GET) \
  OPERATION(OP_INVOKE) \
  OPERATION(OP_INHERIT) OPERATION(OP_SUPER) \
  OPERATION(OP_EMPTY) \
  OPERATION(OP_EXIT) 

#define ENUMERATE(ENUMERATION) ENUMERATION,
#define STRINGIFY(STRING) #STRING,
#define COMPUTED(GOTO) &&GOTO,

typedef enum {
  FOREACH(ENUMERATE)
} Operations;

typedef struct {
  int count;
  int capacity;
  uint8_t* code;

  int* lines;

  Constants constants;
} Chunk;

void initialize_chunk(Chunk* chunk, VM* vm);
void free_chunk(Chunk* chunk);
void write_chunk(Chunk* chunk, uint8_t byte, int line);

int add_constant(Chunk* chunk, Value value);

#endif