#ifndef TOKENIZER_H
#define TOKENIZER_H

#include "common.h"

typedef enum {
  TOKEN_EOF, TOKEN_ERROR, TOKEN_EMPTY, TOKEN_EXIT,
  TOKEN_IDENTIFIER,
  TOKEN_NUMBER, TOKEN_STRING, TOKEN_VOID, TOKEN_UNDEFINED,
  TOKEN_TRUE, TOKEN_FALSE,
  TOKEN_PLUS, TOKEN_MINUS, TOKEN_ASTERISK, TOKEN_SLASH, TOKEN_CARET,
  TOKEN_AND, TOKEN_OR, TOKEN_NOT,
  TOKEN_EQUAL, TOKEN_NOT_EQUAL, 
  TOKEN_GREATER, TOKEN_LESS, TOKEN_GREATER_EQUAL, TOKEN_LESS_EQUAL,
  TOKEN_COMMA, TOKEN_COLON, TOKEN_DOT,
  TOKEN_OPEN_PARENTHESES, TOKEN_CLOSE_PARENTHESES,
  TOKEN_OPEN_BRACKETS, TOKEN_CLOSE_BRACKETS,
  TOKEN_OPEN_BRACES, TOKEN_CLOSE_BRACES,
  TOKEN_ASSIGN, 
  TOKEN_INCREMENT, TOKEN_DECREMENT,
  TOKEN_SET,
  TOKEN_GLOBAL,
  TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_DO, TOKEN_FOR,
  TOKEN_DEFINE, TOKEN_RETURN,
  TOKEN_SEMICOLON
} Types; 

typedef struct {
  Types type;
  const char* start;
  int length;
  int line;
} Token;

typedef struct {
  const char* start;
  const char* current;
  int line;
} Tokenizer;

void set_tokenizer(Tokenizer* tokenizer, const char* source);

Token scan(Tokenizer* tokenizer);

#endif